#Labels
all_labels<- list(c('Secure','Struggling'),
                  c('Secure','Survey population'),
                  c('Struggling','Survey population'),
                  c('Highly Secure','Secure but worried','Struggling to keep up','Falling behind'),
                  c('Highly Secure','Survey population'),
                  c('Secure but worried','Survey population'),
                  c('Struggling to keep up','Survey population'),
                  c('Falling behind','Survey population'),
                  c('Secure','Struggling'),
                  c('Secure','Survey population'),
                  c('Struggling','Survey population'),
                  c('Secure 1','Secure 2','Struggling 1','Struggling 2'),
                  c('Secure','Struggling'),
                  c('Secure','Survey population'),
                  c('Struggling','Survey population'),
                  c('Highly Secure','Secure but worried','Struggling to keep up','Falling behind'),
                  c('Highly Secure','Survey population'),
                  c('Secure but worried','Survey population'),
                  c('Struggling to keep up','Survey population'),
                  c('Falling behind','Survey population')
)

allcolours<- list(c('#88419D','#FEB24C'),
                  c('#88419D','#969696'),
                  c('#FEB24C','#969696'),
                  c('#810F7C','#8C6BB1','#FED976','#FD8D3C'),
                  c('#810F7C','#969696'),
                  c('#8C6BB1','#969696'),
                  c('#FED976','#969696'),
                  c('#FD8D3C','#969696'),
                  c('#88419D','#FEB24C'),
                  c('#88419D','#969696'),
                  c('#FEB24C','#969696'),
                  c('#810F7C','#8C6BB1','#FED976','#FD8D3C'),
                  c('#88419D','#FEB24C'),
                  c('#88419D','#969696'),
                  c('#FEB24C','#969696'),
                  c('#810F7C','#8C6BB1','#FED976','#FD8D3C'),
                  c('#810F7C','#969696'),
                  c('#8C6BB1','#969696'),
                  c('#FED976','#969696'),
                  c('#FD8D3C','#969696')
)

#reverse label and colour order when using coord_flip() for bar charts
revlabels<- list(c('Struggling','Secure'),
                 c('Survey population','Secure'),
                 c('Survey population','Struggling'),
                 c('Falling behind','Struggling to keep up','Secure but worried','Highly Secure'),
                 c('Survey population','Highly Secure'),
                 c('Survey population','Secure but worried'),
                 c('Survey population','Struggling to keep up'),
                 c('Survey population','Falling behind'),
                 c('Struggling','Secure'),
                 c('Survey population','Secure'),
                 c('Survey population','Struggling'),
                 c('Struggling 2','Struggling 1','Secure 2','Secure 1'),
                 c('Struggling','Secure'),
                 c('Survey population','Secure'),
                 c('Survey population','Struggling'),
                 c('Falling behind','Struggling to keep up','Secure but worried','Highly Secure'),
                 c('Survey population','Highly Secure'),
                 c('Survey population','Secure but worried'),
                 c('Survey population','Struggling to keep up'),
                 c('Survey population','Falling behind')
)

revcolours<- list(c('#FEB24C','#88419D'),
                  c('#969696','#88419D'),
                  c('#969696','#FEB24C'),
                  c('#FD8D3C','#FED976','#8C6BB1','#810F7C'),
                  c('#969696','#810F7C'),
                  c('#969696','#8C6BB1'),
                  c('#969696','#FED976'),
                  c('#969696','#FD8D3C'),
                  c('#FEB24C','#88419D'),
                  c('#969696','#88419D'),
                  c('#969696','#FEB24C'),
                  c('#FD8D3C','#FED976','#8C6BB1','#810F7C'),
                  c('#FEB24C','#88419D'),
                  c('#969696','#88419D'),
                  c('#969696','#FEB24C'),
                  c('#FD8D3C','#FED976','#8C6BB1','#810F7C'),
                  c('#969696','#810F7C'),
                  c('#969696','#8C6BB1'),
                  c('#969696','#FED976'),
                  c('#969696','#FD8D3C')
)

#histogram colours
histcolours<- list('#969696',
                   c('#969696','#88419D'),
                   c('#969696','#FEB24C'),
                   '#969696',
                   c('#969696','#810F7C'),
                   c('#969696','#8C6BB1'),
                   c('#969696','#FED976'),
                   c('#969696','#FD8D3C'),
                   '#969696',
                   c('#969696','#88419D'),
                   c('#969696','#FEB24C'),
                   '#969696',
                   '#969696',
                   c('#969696','#88419D'),
                   c('#969696','#FEB24C'),
                   '#969696',
                   c('#969696','#810F7C'),
                   c('#969696','#8C6BB1'),
                   c('#969696','#FED976'),
                   c('#969696','#FD8D3C')
)

#percentage text colours
percentcolours<- list('#969696',
                      '#88419D',
                      '#FEB24C',
                      '#969696',
                      '#810F7C',
                      '#8C6BB1',
                      '#FED976',
                      '#FD8D3C',
                      '#969696',
                      '#88419D',
                      '#FEB24C',
                      '#969696',
                      '#969696',
                      '#88419D',
                      '#FEB24C',
                      '#969696',
                      '#810F7C',
                      '#8C6BB1',
                      '#FED976',
                      '#FD8D3C')

percentlabels<- list('',
                     'Secure',
                     'Struggling',
                     '',
                     'Highly Secure',
                     'Secure but worried',
                     'Struggling to keep up',
                     'Falling behind',
                     '',
                     'Secure',
                     'Struggling',
                     '',
                     '',
                     'Secure',
                     'Struggling',
                     '',
                     'Highly Secure',
                     'Secure but worried',
                     'Struggling to keep up',
                     'Falling behind')

billscclabels <- c('falling behind\non some',
                   'financial problems,\nfallen behind\nwith many',
                   'keeping up,\nconstant struggle',
                   'keeping up,\nstruggle from\ntime to time',
                   'keeping up\nwithout much\ndifficulty')

savinglabels <- c('no -\ndefinitely not',
                  'no -\nnot particularly',
                  'yes -\nsignificant increase',
                  'yes -\nslightly increase')

mdsexplain <- 'We used a technique called Multidimensional Scaling to group households together based on response to survey questions. On this plot, households placed closer together have more similar answers to questions related to financial outlook.'
#mdstitle <- 'Using a technique called multidimensional scaling, households are measured how close they are to each other based on the similarity'

