#Labels
all_labels<- list(c('Secure','Struggling'),
                  c('Secure','Survey population'),
                  c('Struggling','Survey population'),
                  c('Highly secure','Conservative secure','Struggling but managing','Falling behind'),
                  c('Highly secure','Survey population'),
                  c('Conservative secure','Survey population'),
                  c('Struggling but managing','Survey population'),
                  c('Falling behind','Survey population'),
                  c('Secure','Struggling'),
                  c('Secure','Survey population'),
                  c('Struggling','Survey population'),
                  c('Secure 1','Secure 2','Struggling 1','Struggling 2'),
                  c('Secure','Struggling'),
                  c('Secure','Survey population'),
                  c('Struggling','Survey population'),
                  c('Highly Secure','Secure but worried','Struggling to keep up','Falling behind'),
                  c('Highly Secure','Survey population'),
                  c('Secure but worried','Survey population'),
                  c('Struggling to keep up','Survey population'),
                  c('Falling behind','Survey population')
)

allcolours<- list(c('#238443','#D7301F'),
                  c('#238443','#969696'),
                  c('#D7301F','#969696'),
                  c('#006837','#78C679','#FC8D59','#B30000'),
                  c('#006837','#969696'),
                  c('#78C679','#969696'),
                  c('#FC8D59','#969696'),
                  c('#B30000','#969696'),
                  c('#238443','#D7301F'),
                  c('#238443','#969696'),
                  c('#D7301F','#969696'),
                  c('#006837','#78C679','#FC8D59','#B30000'),
                  c('#238443','#D7301F'),
                  c('#238443','#969696'),
                  c('#D7301F','#969696'),
                  c('#006837','#78C679','#FC8D59','#B30000'),
                  c('#006837','#969696'),
                  c('#78C679','#969696'),
                  c('#FC8D59','#969696'),
                  c('#B30000','#969696')
)

#reverse label and colour order when using coord_flip() for bar charts
revlabels<- list(c('Struggling','Secure'),
                 c('Survey population','Secure'),
                 c('Survey population','Struggling'),
                 c('Falling behind','Struggling but managing','Conservative secure','Highly secure'),
                 c('Survey population','Highly secure'),
                 c('Survey population','Conservative secure'),
                 c('Survey population','Struggling but managing'),
                 c('Survey population','Falling behind'),
                 c('Struggling','Secure'),
                 c('Survey population','Secure'),
                 c('Survey population','Struggling'),
                 c('Struggling 2','Struggling 1','Secure 2','Secure 1'),
                 c('Struggling','Secure'),
                 c('Survey population','Secure'),
                 c('Survey population','Struggling'),
                 c('Falling behind','Struggling to keep up','Secure but worried','Highly Secure'),
                 c('Survey population','Highly Secure'),
                 c('Survey population','Secure but worried'),
                 c('Survey population','Struggling to keep up'),
                 c('Survey population','Falling behind')
)

revcolours<- list(c('#D7301F','#238443'),
                  c('#969696','#238443'),
                  c('#969696','#D7301F'),
                  c('#B30000','#FC8D59','#78C679','#006837'),
                  c('#969696','#006837'),
                  c('#969696','#78C679'),
                  c('#969696','#FC8D59'),
                  c('#969696','#B30000'),
                  c('#D7301F','#238443'),
                  c('#969696','#238443'),
                  c('#969696','#D7301F'),
                  c('#B30000','#FC8D59','#78C679','#006837'),
                  c('#D7301F','#238443'),
                  c('#969696','#238443'),
                  c('#969696','#D7301F'),
                  c('#B30000','#FC8D59','#78C679','#006837'),
                  c('#969696','#006837'),
                  c('#969696','#78C679'),
                  c('#969696','#FC8D59'),
                  c('#969696','#B30000')
)

#histogram colours
histcolours<- list('#969696',
                   c('#969696','#238443'),
                   c('#969696','#D7301F'),
                   '#969696',
                   c('#969696','#006837'),
                   c('#969696','#78C679'),
                   c('#969696','#FC8D59'),
                   c('#969696','#B30000'),
                   '#969696',
                   c('#969696','#238443'),
                   c('#969696','#D7301F'),
                   '#969696',
                   '#969696',
                   c('#969696','#238443'),
                   c('#969696','#D7301F'),
                   '#969696',
                   c('#969696','#006837'),
                   c('#969696','#78C679'),
                   c('#969696','#FC8D59'),
                   c('#969696','#B30000')
)

#percentage text colours
percentcolours<- list('#969696',
                      '#238443',
                      '#D7301F',
                      '#969696',
                      '#006837',
                      '#78C679',
                      '#FC8D59',
                      '#B30000',
                      '#969696',
                      '#238443',
                      '#D7301F',
                      '#969696',
                      '#969696',
                      '#238443',
                      '#D7301F',
                      '#969696',
                      '#006837',
                      '#78C679',
                      '#FC8D59',
                      '#B30000')

percentlabels<- list('',
                     'Secure',
                     'Struggling',
                     '',
                     'Highly Secure',
                     'Conservative secure',
                     'Struggling but managing',
                     'Falling behind',
                     '',
                     'Secure',
                     'Struggling',
                     '',
                     '',
                     'Secure',
                     'Struggling',
                     '',
                     'Highly Secure',
                     'Secure but worried',
                     'Struggling to keep up',
                     'Falling behind')

mapcolorshigh <- list('',
                   '#238443',
                   '#D7301F',
                   '',
                   '#006837',
                   '#78C679',
                   '#FC8D59',
                   '#B30000',
                   '',
                   '#238443',
                   '#D7301F',
                   '',
                   '',
                   '#238443',
                   '#D7301F',
                   '',
                   '#006837',
                   '#78C679',
                   '#FC8D59',
                   '#B30000')

billscclabels <- c('falling behind\non some',
                   'financial problems,\nfallen behind\nwith many',
                   'keeping up,\nconstant struggle',
                   'keeping up,\nstruggle from\ntime to time',
                   'keeping up\nwithout much\ndifficulty')

savinglabels <- c('no -\ndefinitely not',
                  'no -\nnot particularly',
                  'yes -\nsignificant increase',
                  'yes -\nslightly increase')


mdsexplain <- 'We used a technique called Multidimensional Scaling to group households together based on responses to survey questions. On this plot, each circle represents a household and households placed closer together have more similar answers to questions related to financial attitude and outlook. The most informative questions are shown on the right panel.'
mdsexplain2 <- 'We can observe whether financial attitudes of households correspond to their actual financial position by sizing the circles according to variables such as income and debt. These can be selected at the rightmost navigation panel.'
demogexplain <- "We can observe what kinds of households define each type by corresponding to their socio-demographic characteristics. The map shows which UK regions the household type is overrepresented compared to the survey population, while the right panel displays attributes according to individual or household status."
#mdstitle <- 'Using a technique called multidimensional scaling, households are measured how close they are to each other based on the similarity'

